sequenceDiagram
    participant A as Poll Owner
    participant B as Blind-Poll Contract
    participant C as BPT-Token Contract
    participant D as Participant


    A ->> B: Craete a poll
    A ->> C: Approve allowance for poll contract
    A ->> D: Share returned poll ID
    D ->> B: Query poll detail
    B -->> D: Poll detail
    D ->> B: Submit sealed answer
    A ->> B: Query total of received answers
    A ->> B: Close the poll
    D ->> B: Reveal answer and claim rewards
    B ->> C: Transfer from creator's allowance
    C -->> D: Received BPT tokens
    A ->> B: Collect answers
    A ->> A: Conduct off-chain statistics